### ISSUE TITLE
"'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them"

### ISSUE THREAD

**Issue by xPaw** [birchill/bugsnag-zero#109]
I'm getting this error reported from Firefox 115. It's try-caught here:

https://github.com/birchill/bugsnag-zero/blob/bcb3a6a8b81e7ce4c363667de9b2424621ac6cb6/src/to-exception.ts#L123-L130

However it seems that it still gets reported to bugsnag anyway. I am not sure what the repro for this is though.

**Comment by birtles** [comment]
Thank you for reporting this! (I didn't know anyone else was actually using this library!)

That's quite odd. Do you see the message in the console? If so, could you send me a screenshot of that?

Just running some sample code in Firefox 117 it looks like we can catch the exception without it being printed to the console: https://jsbin.com/goyiwatuzo/edit?html,js,console,output

Maybe something else is catching it though?

I looked at the official Bugsnag client but it appears to be using `StackGenerator.backtrace()` ([source](https://github.com/bugsnag/bugsnag-js/blob/bc61c6e3a06512982384d4a4d7ede88968aec18b/packages/core/event.js#L168-L172)) which accesses `arguments.callee` without wrapping it in `try ... catch` ([source](https://github.com/stacktracejs/stack-generator/blob/d13f852474a1736a82818b904f3e7d3d79b0b627/stack-generator.js#L23)). Maybe that particular code is not in strict mode though?

**Comment by xPaw** [comment]
It's being reported to bugsnag as an error from other users, I don't see it myself so I don't know how to reproduce it yet.

**Comment by birtles** [comment]
Oh, interesting. I've never come across that being reported despite using bugsnag-zero on several different projects, some with 10,000s of users.

Are you sure the error is coming from bugsnag-zero and not some other part of the app? For example, if you also have the official bugsnag client loaded I think it could trigger this.

Any extra information about the report delivered to bugsnag would be helpful. Thanks!

**Comment by xPaw** [comment]
Yes the trace looks to be from bugsnag-zero load method, I don't use the official reporter. I'll try to get more details or dig into it for a repro.

**Comment by birtles** [comment]
Thank you!

**Comment by xPaw** [comment]
I looked at the trace more carefully since it's minified, and the line position actually points to `curr` in the loop, after the try catch.

```js
try{e=arguments.callee}catch{return[]}for(;e&&n.length<Q&&e.arguments;)
```

Specifically `for(;e` here. I am using esbuild to minify but I don't think that matters here.

**Comment by birtles** [comment]
It seems odd that if accessing `.callee` here threw an error, we should have returned.

I wonder if that's just because bugsnag-zero is not as clever as the official client in removing itself from the stack. That is, I wonder if it is just correctly reporting an error elsewhere in the app (something else that tries to read `caller` or `callee` or `arguments`) and the stack `bugsnag-zero` is reporting is making it look like it is originating from `bugsnag-zero`?

**Comment by xPaw** [comment]
I don't use callee or arguments in my code. It is possible that any browser extension that is injecting some code could be reading it, but the trace does appear to be correct within bugsnag-zero, so I don't think it's that.

Here I reproduced it: https://jsbin.com/hafahugega/edit?html,js,console,output

**Comment by birtles** [comment]
As far as I can tell, it doesn't even _need_ to access `curr['arguments']` there. As in, I think we could just drop the `&& curr['arguments']` check altogether.

As far as I can tell, it's only needed in `stack-generator` because it tries to add arguments to stack frames (see https://github.com/stacktracejs/stack-generator/pull/4) but bugsnag's API doesn't have arguments in stack frames so I don't think we need that check.

**Comment by xPaw** [comment]
That sounds fine. I'm just curious why it's trying to generate a trace from unhandledrejection, because it won't be a very useful trace right?

**Comment by birtles** [comment]
Right. I don't think there's any foolproof way to get a trace from an unhandledrejection. [`PromiseRejectionEvent.reason`](https://developer.mozilla.org/en-US/docs/Web/API/PromiseRejectionEvent/reason) just contains whatever was passed to `Promise.reject()`.

So if there is code doing `throw 'failure'` or `reject('failure')` you'll just get the string `'failure'`. If you're using one of the standard `Error` objects (e.g. `throw new Error('failure')`) I think [`.stack`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/stack) will get filled in. For custom errors objects, though, you have to use the non-standard `captureStackTrace` in the error's constructor and I think that might be a V8-only thing too.

**Comment by xPaw** [comment]
That is unfortunate because I believe this particular failure is coming from a browser extension, so I have no control over it, and seemingly won't be able to filter it out because it has no trace that includes chrome-extension.

**Comment by birtles** [comment]
Yeah, that's very annoying. I have a similar problem with CSP errors produced by browser extensions. It makes all CSP reports less useful.

I don't suppose there's anything else about the failure that you can use to filter it out? The specific error message, etc.?

**Comment by xPaw** [comment]
I can probably filter on `error.name = 'InvalidError'` after this particular issue is fixed.

**Comment by birtles** [comment]
Ok, I've pushed 0.6.1 now. Let's see if that fixes it.

**Comment by birtles** [comment]
Hopefully fixed by 9ad501614bde5d664e97463c8a2b5aef4f51f9c9

**Comment by xPaw** [comment]
Thanks! I'll monitor.

**Comment by xPaw** [comment]
Just FYI, the non-error parameter is not always a string, `InvalidError unhandledrejection received a non-error. See "unhandledrejection" tab for more detail.`

So `non-error parameter` can end up being `[object Object]` in Bugsnag.

**Comment by birtles** [comment]
Yeah, we should do a better job of handling that. I saw a neat library for stringifying arbitrary objects in a safe way but I was afraid it would swell the package size too much so I haven't included it.

**Comment by birtles** [comment]
For what it's worth, it tries pretty hard to extract a useful error from whatever it gets:

https://github.com/birchill/bugsnag-zero/blob/22b7803dfd8c72d7839960d406d374375a0dc05e/src/to-exception.ts#L45-L90

But then if that fails, it just dumps the error as `'non-error parameter': String(maybeError)`

As best I can tell, the official client only handles `null` and `undefined`: https://github.com/bugsnag/bugsnag-js/blob/bc61c6e3a06512982384d4a4d7ede88968aec18b/packages/core/event.js#L208-L222

Ideally we'd use something like [safe-stable-stringify](https://github.com/BridgeAR/safe-stable-stringify) or [javascript-stringify](https://github.com/blakeembrey/javascript-stringify) or something like that but it will increase the bundle size a bit. Maybe we can adapt one to just what we need.

**Comment by xPaw** [comment]
I particularly don't care because I just completely ignored `InvalidError` in `onError` because my code only throws `Error` objects and everything else is just browser extension noise.
