### ISSUE TITLE
fetch() doesn't work when using `URL` object

### ISSUE THREAD

**Issue by xPaw** [birchill/bugsnag-zero#132]
`fetch(new URL('/', location.href))`

It throws here because `url` is undefined:

https://github.com/birchill/bugsnag-zero/blob/3828de783fb3325be7f3543396f3eae7a3383f01/src/fetch-breadcrumbs.ts#L69

It will fail for `Request` objects too.

**Comment by birtles** [comment]
Thanks! Should be fixed in 0.6.7 I hope!
